version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    container_name: doctorhub-db
    environment:
      POSTGRES_USER: doctorhub
      POSTGRES_PASSWORD: doctorhub
      POSTGRES_DB: doctorhub_dev
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - doctorhub-net

volumes:
  postgres_data:

networks:
  doctorhub-net:
    driver: bridge
